### ISSUE TITLE
Requires framehandler.h

### ISSUE THREAD

**Issue by jimwsmith** [cterwilliger/VeDirectFrameHandler#4]
This code looks to be just what I am looking for but on compiling it fails asking from framehandler.h file which I have researched and cannot find anywhere.

**Comment by cterwilliger** [comment]
Sorry, missed that I changed the filenames before upload.  For now, just rename the file VEDirectFrameHandler.h to framehandler.h

**Comment by cterwilliger** [comment]
changed #include references from "framehandler.h" to "VeDirectFrameHandler.h"
